- name: Disable auto update package lists
  become: true
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Update-Package-Lists "1";'
    line: 'APT::Periodic::Update-Package-Lists "0";'

- name: Disabling unnatended upgrades
  become: true
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Unattended-Upgrade "1";'
    line: 'APT::Periodic::Unattended-Upgrade "0";'
